# Prepare Georgian Speech Data for Whisper Fine-tuning
This notebook loads the Common Voice Georgian dataset and prepares it for training.

In [4]:
import pandas as pd
import os
from pathlib import Path
import librosa
import numpy as np

# Dataset paths
DATA_DIR = Path("cv-corpus-23.0-2025-09-05/ka")
CLIPS_DIR = DATA_DIR / "clips"
TRAIN_TSV = DATA_DIR / "train.tsv"
TEST_TSV = DATA_DIR / "test.tsv"
DEV_TSV = DATA_DIR / "dev.tsv"

In [5]:
# !pip install openai-whisper transformers datasets accelerate jiwer librosa soundfile torch torchaudio gradio pandas

In [6]:
# Load the training data
train_df = pd.read_csv(TRAIN_TSV, sep='\t')
test_df = pd.read_csv(TEST_TSV, sep='\t')
dev_df = pd.read_csv(DEV_TSV, sep='\t')

print(f"Training samples: {len(train_df)}")
print(f"Test samples: {len(test_df)}")
print(f"Dev samples: {len(dev_df)}")
print("\nColumns:", train_df.columns.tolist())
print("\nFirst few rows:")
train_df.head()

Training samples: 62845
Test samples: 13126
Dev samples: 12978

Columns: ['client_id', 'path', 'sentence_id', 'sentence', 'sentence_domain', 'up_votes', 'down_votes', 'age', 'gender', 'accents', 'variant', 'locale', 'segment']

First few rows:

,client_id,path,sentence_id,sentence,sentence_domain,up_votes,down_votes,age,gender,accents,variant,locale,segment
0,4747a228cee75d461612787a5de1c7360d49a474304a0b...,common_voice_ka_36515885.mp3,1c48e571ef84acb53ec36962ec93def0685358851ac20c...,ის პარიზში ცხოვრობდა ცნობილ ვარსკვლავ სტელასთა...,NaN,2,0,twenties,female_feminine,NaN,NaN,ka,NaN
1,4747a228cee75d461612787a5de1c7360d49a474304a0b...,common_voice_ka_36515886.mp3,1d5cdd46e5b2ad566fcae5b48a562cb6777ef70cae675b...,თუმცა ეს არ მოსწონს ვიქტორიას შვილებს.,NaN,2,0,twenties,female_feminine,NaN,NaN,ka,NaN
2,4747a228cee75d461612787a5de1c7360d49a474304a0b...,common_voice_ka_36515887.mp3,1d208df853547c7aca779de6bcef35acf0e54dbbd96dc5...,"იგი დაკრძალეს ქმრის გვერდით, სტოკჰოლმის სამეფო...",NaN,2,0,twenties,female_feminine,NaN,NaN,ka,NaN
3,4747a228cee75d461612787a5de1c7360d49a474304a0b...,common_voice_ka_36515928.mp3,1c407be28c1e22f3b6050c7f1c69e477442b91feb8ea81...,"მიედინება ვიწრო, ღრმა ხეობაში, აჩენს ჭორომებსა...",NaN,2,0,twenties,female_feminine,NaN,NaN,ka,NaN
4,4747a228cee75d461612787a5de1c7360d49a474304a0b...,common_voice_ka_36515929.mp3,1d88c4b2e634a6c2f07b31b4318e8267368048728a0da5...,მისი ადრეული მოთხრობები იბეჭდებოდა სხვადასხვა ...,NaN,2,0,twenties,female_feminine,NaN,NaN,ka,NaN

In [7]:
# Check audio files exist and get statistics
def check_audio_files(df, clips_dir):
    existing = []
    durations = []
    
    for idx, row in df.iterrows():
        audio_path = clips_dir / row['path']
        if audio_path.exists():
            existing.append(True)
            # Get duration
            try:
                duration = librosa.get_duration(path=str(audio_path))
                durations.append(duration)
            except:
                durations.append(0)
        else:
            existing.append(False)
            durations.append(0)
        
        if idx % 1000 == 0:
            print(f"Checked {idx}/{len(df)} files...")
    
    df['exists'] = existing
    df['duration'] = durations
    return df

print("Checking training files...")
train_df = check_audio_files(train_df, CLIPS_DIR)
print(f"\nExisting training files: {train_df['exists'].sum()}/{len(train_df)}")
print(f"Total training duration: {train_df['duration'].sum()/3600:.2f} hours")

Checking training files...
Checked 0/62845 files...
Checked 1000/62845 files...
Checked 2000/62845 files...
Checked 3000/62845 files...
Checked 4000/62845 files...
Checked 5000/62845 files...
Checked 6000/62845 files...
Checked 7000/62845 files...
Checked 8000/62845 files...
Checked 9000/62845 files...
Checked 10000/62845 files...
Checked 11000/62845 files...
Checked 12000/62845 files...
Checked 13000/62845 files...
Checked 14000/62845 files...
Checked 15000/62845 files...
Checked 16000/62845 files...
Checked 17000/62845 files...
Checked 18000/62845 files...
Checked 19000/62845 files...
Checked 20000/62845 files...
Checked 21000/62845 files...
Checked 22000/62845 files...
Checked 23000/62845 files...
Checked 24000/62845 files...
Checked 25000/62845 files...
Checked 26000/62845 files...
Checked 27000/62845 files...
Checked 28000/62845 files...
Checked 29000/62845 files...
Checked 30000/62845 files...
Checked 31000/62845 files...
Checked 32000/62845 files...
Checked 33000/62845 files...
Checked 34000/62845 files...
Checked 35000/62845 files...
Checked 36000/62845 files...
Checked 37000/62845 files...
Checked 38000/62845 files...
Checked 39000/62845 files...
Checked 40000/62845 files...
Checked 41000/62845 files...
Checked 42000/62845 files...
Checked 43000/62845 files...
Checked 44000/62845 files...
Checked 45000/62845 files...
Checked 46000/62845 files...
Checked 47000/62845 files...
Checked 48000/62845 files...
Checked 49000/62845 files...
Checked 50000/62845 files...
Checked 51000/62845 files...
Checked 52000/62845 files...
Checked 53000/62845 files...
Checked 54000/62845 files...
Checked 55000/62845 files...
Checked 56000/62845 files...
Checked 57000/62845 files...
Checked 58000/62845 files...
Checked 59000/62845 files...
Checked 60000/62845 files...
Checked 61000/62845 files...
Checked 62000/62845 files...

Existing training files: 62845/62845
Total training duration: 0.00 hours

In [11]:
# Filter only existing files
train_df_clean = train_df[train_df['exists']].copy()
test_df_clean = test_df[test_df['exists']].copy() if 'exists' in test_df.columns else test_df.copy()

# Create simplified dataset
train_data = train_df_clean[['path', 'sentence']].copy()
train_data['audio_path'] = train_data['path'].apply(lambda x: str(CLIPS_DIR / x))
train_data = train_data[['audio_path', 'sentence']]

print(f"Clean training samples: {len(train_data)}")
print("\nSample data:")
train_data.head()

Clean training samples: 62845

Sample data:

,audio_path,sentence
0,cv-corpus-23.0-2025-09-05/ka/clips/common_voic...,ის პარიზში ცხოვრობდა ცნობილ ვარსკვლავ სტელასთა...
1,cv-corpus-23.0-2025-09-05/ka/clips/common_voic...,თუმცა ეს არ მოსწონს ვიქტორიას შვილებს.
2,cv-corpus-23.0-2025-09-05/ka/clips/common_voic...,"იგი დაკრძალეს ქმრის გვერდით, სტოკჰოლმის სამეფო..."
3,cv-corpus-23.0-2025-09-05/ka/clips/common_voic...,"მიედინება ვიწრო, ღრმა ხეობაში, აჩენს ჭორომებსა..."
4,cv-corpus-23.0-2025-09-05/ka/clips/common_voic...,მისი ადრეული მოთხრობები იბეჭდებოდა სხვადასხვა ...

In [12]:
# Save processed data
train_data.to_csv('train_processed.csv', index=False)
print("Saved processed training data to train_processed.csv")

Saved processed training data to train_processed.csv

In [13]:
# Statistics
print("\n=== Dataset Statistics ===")
print(f"Total samples: {len(train_data)}")
print(f"Total duration: {train_df_clean['duration'].sum()/3600:.2f} hours")
print(f"Average duration: {train_df_clean['duration'].mean():.2f} seconds")
print(f"Min duration: {train_df_clean['duration'].min():.2f} seconds")
print(f"Max duration: {train_df_clean['duration'].max():.2f} seconds")

# Text statistics
print(f"\nAverage text length: {train_data['sentence'].str.len().mean():.2f} characters")

=== Dataset Statistics ===
Total samples: 62845
Total duration: 0.00 hours
Average duration: 0.00 seconds
Min duration: 0.00 seconds
Max duration: 0.00 seconds

Average text length: 65.01 characters

In [15]:
import whisper
model = whisper.load_model("small")
result = model.transcribe("cv-corpus-23.0-2025-09-05/ka/clips/common_voice_ka_21298144.mp3", language="ka")
print(result["text"])

100%|███████████████████████████████████████| 461M/461M [00:08<00:00, 56.1MiB/s]
/Users/lana/.pyenv/versions/3.8.10/lib/python3.8/site-packages/whisper/transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

 ᶜᶤᠤ ᶒᶤᠤ ᷀ ᶁᠤ ớ� slight